version: '3'

services:
        db:
                image: mysql:5.7
                container_name: db
                env_file:
                        - vars.env
                ports:
                        - 3306:3306
                volumes:
                        - ./db/data:/var/lib/mysql
                        - ./db/init:/docker-entrypoint-initdb.d/:ro


        server:
                build:
                        context: .
                        dockerfile: ./Dockerfile
                container_name: server
                ports:
                        - 80:80
                depends_on:
                        - db      
